// <auto-generated />
using API_TD1_1.Models.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API_TD1_1.Migrations
{
    [DbContext(typeof(ProduitDbContext))]
    partial class ProduitDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API_TD1_1.Models.EntityFramework.Marque", b =>
                {
                    b.Property<int>("IdMarque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("mar_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMarque"));

                    b.Property<string>("NomMarque")
                        .HasMaxLength(85)
                        .HasColumnType("character varying(85)")
                        .HasColumnName("mar_nom");

                    b.HasKey("IdMarque")
                        .HasName("pk_mar");

                    b.ToTable("t_e_marque_mar");
                });

            modelBuilder.Entity("API_TD1_1.Models.EntityFramework.Produit", b =>
                {
                    b.Property<int>("IdProduit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pro_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProduit"));

                    b.Property<string>("Description")
                        .HasMaxLength(905)
                        .HasColumnType("character varying(905)")
                        .HasColumnName("pro_desc");

                    b.Property<int>("IdMarque")
                        .HasColumnType("integer")
                        .HasColumnName("pro_idmarque");

                    b.Property<int>("IdTypeProduit")
                        .HasColumnType("integer")
                        .HasColumnName("pro_idtype");

                    b.Property<string>("NomPhoto")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("pro_nomphoto");

                    b.Property<string>("NomProduit")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("pro_nom");

                    b.Property<int>("SockMax")
                        .HasColumnType("integer")
                        .HasColumnName("pro_stockmax");

                    b.Property<int>("StockMin")
                        .HasColumnType("integer")
                        .HasColumnName("pro_stockmin");

                    b.Property<int>("StockReel")
                        .HasColumnType("integer")
                        .HasColumnName("pro_stockreel");

                    b.Property<string>("UriPhoto")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("pro_uriphoto");

                    b.HasKey("IdProduit")
                        .HasName("pk_pro");

                    b.HasIndex("IdMarque");

                    b.HasIndex("IdTypeProduit");

                    b.ToTable("t_e_produit_pro");
                });

            modelBuilder.Entity("API_TD1_1.Models.EntityFramework.TypeProduit", b =>
                {
                    b.Property<int>("IdTypeProduit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("typ_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTypeProduit"));

                    b.Property<string>("NomTypeProduit")
                        .HasMaxLength(85)
                        .HasColumnType("character varying(85)")
                        .HasColumnName("typ_nom");

                    b.HasKey("IdTypeProduit")
                        .HasName("pk_typ");

                    b.ToTable("t_e_typeproduit_typ");
                });

            modelBuilder.Entity("API_TD1_1.Models.EntityFramework.Produit", b =>
                {
                    b.HasOne("API_TD1_1.Models.EntityFramework.Marque", "MarqueNavigation")
                        .WithMany("ProduitsNavigation")
                        .HasForeignKey("IdMarque")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pro_mar");

                    b.HasOne("API_TD1_1.Models.EntityFramework.TypeProduit", "TypeProduitNavigation")
                        .WithMany("ProduitsNavigation")
                        .HasForeignKey("IdTypeProduit")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pro_typ");

                    b.Navigation("MarqueNavigation");

                    b.Navigation("TypeProduitNavigation");
                });

            modelBuilder.Entity("API_TD1_1.Models.EntityFramework.Marque", b =>
                {
                    b.Navigation("ProduitsNavigation");
                });

            modelBuilder.Entity("API_TD1_1.Models.EntityFramework.TypeProduit", b =>
                {
                    b.Navigation("ProduitsNavigation");
                });
#pragma warning restore 612, 618
        }
    }
}
